name: Validate Workflow Syntax

on:
  push:
    paths:
      - '**/*.yml'

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Workflow Syntax
        run: |
          find . -name '*.yml' -exec sh -c 'yamllint "$0" || exit 0' {} \;
