name: Validate Workflow Syntax

on:
  push:
    branches:
      - '*'

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Workflow Syntax
        run: find . -name '*.yml' -exec yamllint {} +
