name: Local Test

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  local_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests Locally
      run: |
        pytest tests/
