name: Test

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Workflow Syntax
        run: |
          for file in $(find . -name '*.yml'); do
            echo "Validating $file"
            yamllint $file
          done
